pipeline {
    agent {
        node {
            label 'maven'
        }
    }
    environment {
        RHT_OCP4_DEV_USER = 'ugtdvz'
        DEPLOYMENT_STAGE = 'shopping-cart-stage'
        DEPLOYMENT_PRODUCTION = 'shopping-cart-production'
    }
    stages {
        stage('Tests') {
            steps {
                sh '''
                 cd shopping-cart 
                ./mvnw clean test
                '''
            }
        }
        stage('Package') {
            steps {
                sh '''
                     cd shopping-cart
                    ./mvnw package -DskipTests \
                    -Dquarkus.package.type=uber-jar
                '''
                archiveArtifacts 'shopping-cart/target/*.jar'
            }
        }

stage('Build Image') {
    environment { QUAY = credentials('QUAY_USER') } 
    steps {
        sh '''
           cd shopping-cart
           ./mvnw quarkus:add-extension \
            -Dextensions="kubernetes,container-image-jib" 
        '''
        sh '''
             cd shopping-cart
            ./mvnw package -DskipTests -Dquarkus.jib.base-jvm-image=quay.io/redhattraining/do400-java-alpine-openjdk11-jre:latest -Dquarkus.container-image.build=true -Dquarkus.container-image.registry=quay.io -Dquarkus.container-image.group=$QUAY_USR -Dquarkus.container-image.name=do400-deploying-environments -Dquarkus.container-image.username=$QUAY_USR -Dquarkus.container-image.password="$QUAY_PSW" -Dquarkus.container-image.tag=build-${BUILD_NUMBER} -Dquarkus.container-image.push=true 
        '''
    }
}
stage('Deploy - Stage') {
    environment {
        APP_NAMESPACE = "${RHT_OCP4_DEV_USER}-shopping-cart-stage"
        QUAY = credentials('QUAY_USER')
    }
    steps {
        sh """
            oc set image \
            deployment ${DEPLOYMENT_STAGE} \
            shopping-cart-stage=quay.io/${QUAY_USR}/do400-deploying-environments:build-${BUILD_NUMBER} \
            -n ${APP_NAMESPACE} --record
        """
    }
}


    }
}
