pipeline {
    agent {
        node {
            label 'maven'
        }
    }
    stages {
        stage('Tests') {
            steps {
                sh '''
                 cd shopping-cart 
                ./mvnw clean test
                '''
            }
        }
        stage('Package') {
            steps {
                sh '''
                     cd shopping-cart
                    ./mvnw package -DskipTests \
                    -Dquarkus.package.type=uber-jar
                '''
                archiveArtifacts 'shopping-cart/target/*.jar'
            }
        }

stage('Build Image') {
    environment { QUAY = credentials('QUAY_USER') } 
    steps {
        sh '''
           cd shopping-cart
           ./mvnw quarkus:add-extension \
            -Dextensions="kubernetes,container-image-jib" 
        '''
        sh '''
             cd shopping-cart
            ./mvnw package -DskipTests -Dquarkus.jib.base-jvm-image=quay.io/redhattraining/do400-java-alpine-openjdk11-jre:latest -Dquarkus.container-image.build=true -Dquarkus.container-image.registry=quay.io -Dquarkus.container-image.group=$QUAY_USR -Dquarkus.container-image.name=do400-deploying-environments -Dquarkus.container-image.username=$QUAY_USR -Dquarkus.container-image.password="$QUAY_PSW" -Dquarkus.container-image.push=true 
        '''
    }
}


    }
}
